build:
  version: "3.0"

cards:
  message: "Welcome to Bankapp cards related local APIs "
  contactDetails:
    name: "Abhishek - Developer"
    email: "abhi@banker.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932