spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          # search-location: "classpath:/config"
#          search-location: "file:///D://dev_zone_aditya//spring//springboot3//config"
        git:
          uri: "https://github.com/devtechsolution/bank-app-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    web:
      exposure:
        include: "*"

encrypt:
  key: "ABC123DEF456GHI789JKL"

server:
  port: 8071
