server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yaml"
      - "application_prod.yaml"
  profiles:
     active:
       - "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to Bankapp accounts related local APIs "
  contactDetails:
    name: "Aditya Srivastva - Developer"
    email: "aditya@devbank.com"
  onCallSupport:
    - (111) 234-1234
    - (222) 456-1345

