services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - adityasrivastva

  configserverservice:
    image: "adityasrivastva/configserver-s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - adityasrivastva

  accounts:
    image: "adityasrivastva/acc-s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserverservice:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - adityasrivastva
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserverservice:8071/"
      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "adityasrivastva/cards:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserverservice:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - adityasrivastva
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserverservice:8071/"
      SPRING_PROFILES_ACTIVE: default

  cards:
    image: "adityasrivastva/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserverservice:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - adityasrivastva
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserverservice:8071/"
      SPRING_PROFILES_ACTIVE: default

networks:
  adityasrivastva:
    driver: "bridge"